[package]
name = "gen_queries"
version = "0.1.0"
edition = "2024"

[dependencies]
auto_gen_queries = { path = "./auto_gen_queries", package = "auto_gen_queries" }

[build-dependencies]
clorinde = { version = "1.1" }
tokio-postgres = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
temp_container_utils = { path = "../temp_container_utils" }
db_schema_utils = { path = "../db_schema_utils" }
