[package]
name = "votebase"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_ast = { version = "0.44", features = ["transpiling"] }
deno_core = "0.328.0"
# rocket = { version = "0.5" }
reqwest = "0.12"
tokio = { version = "1.40", features = ["full"] }

[build-dependencies]
deno_core = "0.328"
