[workspace]
resolver = "2"
members = [
	"common",
	"cli",
	"bootstrap_cli",
	"server",
	"db_schema_utils",
	"transpile_utils",
	"temp_container_utils",
	# "gen_queries", intentionally leaving this out because it's generated? doesn't seem to need to be included to be imported by common
]

[workspace.dependencies]
argh = "0.1"

deno_core = "0.367.0"
deno_error = "0.7.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", default-features = false }
# serde_jsonc2 = "0.1"
uuid = { version = "*", features = ["serde", "v4"] }
chrono = { version = "*", features = ["serde"] }
tokio = { version = "1.48", features = ["full", "rt"] }
thiserror = "2"
anyhow = "1"
url = "2"
walkdir = "2"
log = "0.4"
include_dir = "0.7"
futures = "0.3"

tokio-postgres = { version = "0.7" }
deadpool-postgres = { version = "0.14" }

predicates = "3"
assert_fs = "1"
# assert_cmd = "2"
