use-workspace-deps = true

[package]
name = "votebase_queries"

[types]
# Applied to all generated structs and postgres types
derive-traits = ["serde::Serialize", "serde::Deserialize"]

# not working?
# [types.type-traits-mapping]
# # Applied to specfic custom postgres types (eg. enums, domains, composites)
# "votebase_catalog.granularity_enum" = ["serde::Deserialize"]
