FROM node:24-slim

# enable pnpm via corepack
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PNPM_HOME/bin:$PATH"
RUN corepack enable

WORKDIR /workspace

COPY tsconfig.votebase-rulesets.json .
COPY common/src/runtime/runtime.ts votebase-runtime.ts

RUN pnpm add -g typescript

# RUN tsc --project tsconfig.votebase-rulesets.json --emitDeclarationOnly votebase-runtime.ts

# consider compiling the runtime file to declarations and

ENTRYPOINT ["tsc", "--project", "tsconfig.votebase-rulesets.json"]
CMD ["--help"]

# "paths": {
# 	"votebase": ["votebase-runtime.ts"]
# },
# "types": ["votebase-runtime.ts"],

# we can avoid the need for a registry or any nonsense if we can:
# - podman build votebase-tsc or whatever image locally, including the tsconfig or libraries we want etc
# - have the actual votebase server or whatever image *save that above exported tarfile*, so that it already comes packaged. this will require podman in podman or podman in docker
# - at server startup (or in the votebase server image itself?) do podman *load* to get the image in the right place, and then the runtime etc can use it

# https://docs.podman.io/en/latest/markdown/podman-save.1.html
# https://docs.podman.io/en/latest/markdown/podman-load.1.html
