# TODO instead of weird gen_queries crate use cargo make with a rust script
# https://sagiegurari.github.io/cargo-make/#usage-task-command-script-task-examplerust
# to build the gen_queries crate, and make it a dependency for test dev run build etc, and use the source tracking to make it not repeat
# https://sagiegurari.github.io/cargo-make/#running-tasks-only-if-sources-changed
# https://sagiegurari.github.io/cargo-make/#usage-installing-dependencies
# https://sagiegurari.github.io/cargo-make/#usage-workspace-support
# cargo make --no-workspace mytask

[config]
default_to_workspace = false
# for tasks you *want* to run individually in members:
# workspace = true


[tasks.do_gen_queries]
command = "cargo"
args = ["run", "-p", "db_schema_utils"]
condition = { files_modified = { input = ["./db_schema_utils/**/*"], output = ["./db_generated/**/*"] } }

[tasks.dev_test]
command = "cargo"
args = ["test", "--", "--nocapture"]

# [tasks.dev]
# command = "cargo"
# args = ["test", "--", "--nocapture"]

# [tasks.test]
# command = "cargo"
# args = ["test", "--", "--nocapture"]
# # dependencies = [""]

# # [tasks.format]
# # install_crate = "rustfmt"
# # command = "cargo"
# # args = ["fmt", "--", "--emit=files"]

# # [tasks.clean]
# # command = "cargo"
# # args = ["clean"]

# # [tasks.build]
# # command = "cargo"
# # args = ["build"]
# # dependencies = ["clean"]

# # [tasks.test]
# # command = "cargo"
# # args = ["test"]
# # dependencies = ["clean"]

# # [tasks.my-flow]
# # dependencies = [
# # 	"format",
# # 	"build",
# # 	"test"
# # ]
