[package]
name = "votebase_bootstrap_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
votebase_common = { path = "../common" }
db_schema_utils = { path = "../db_schema_utils" }

tokio-postgres = { workspace = true }
deadpool-postgres = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
rand = "0.9"
base64 = "0.22"
