[package]
name = "votebase_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
votebase_queries = { path = "../queries" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
postgres-from-row = "0.5"
rand = "0.9"
base64 = "0.22"
sqlparser = { version = "0.56", features = ["visitor"] }
