[package]
name = "votebase_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
votebase_common = { path = "../common" }
temp_container_utils = { path = "../temp_container_utils" }
db_schema_utils = { path = "../db_schema_utils" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
url = { workspace = true }
include_dir = { workspace = true }
argh = { workspace = true }
# serde_jsonc2 = { workspace = true }

[dev-dependencies]
# assert_cmd = { workspace = true }
predicates = { workspace = true }
assert_fs = { workspace = true }
walkdir = { workspace = true }
futures = { workspace = true }
