[package]
name = "temp_container_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { workspace = true }
thiserror = { workspace = true }
# anyhow = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
deadpool-postgres = { workspace = true }
rand = "0.9"
rand_distr = "0.5"
nix = { version = "0.29", features = ["signal"] }

[dev-dependencies]
serial_test = "3"
