[package]
name = "votebase_common"
version = "0.1.0"
edition = "2024"

[dependencies]
transpile_utils = { path = "../transpile_utils" }
db_generated = { path = "../db_generated" }
utils = { path = "../utils" }
deno_core = { workspace = true }
deno_error = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tmpdir = { workspace = true }
log = { workspace = true }
itertools = { workspace = true }

futures = { workspace = true }
walkdir = { workspace = true }
sqlparser = { version = "0.60", features = ["visitor"] }
postgres-from-row = "0.5"
tokio-stream = { workspace = true }
reqwest = "0.12"
hashbrown = { workspace = true }


[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
db_schema_utils = { path = "../db_schema_utils" }
anyhow = { workspace = true }
assert_fs = { workspace = true }

[build-dependencies]
deno_core = { workspace = true }
deno_error = { workspace = true }
transpile_utils = { path = "../transpile_utils" }
