[package]
name = "votebase_common"
version = "0.1.0"
edition = "2024"

[dependencies]
deno_core = { workspace = true }
deno_error = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
transpile_utils = { path = "../transpile_utils" }
reqwest = "0.12"
urlencoding = "2"

futures = { workspace = true }
walkdir = { workspace = true }
sqlparser = { version = "0.59", features = ["visitor"] }
postgres-from-row = "0.5"
futures-util = "0.3"
percent-encoding = { workspace = true }

db_generated = { path = "../db_generated" }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }

[build-dependencies]
deno_core = { workspace = true }
deno_error = { workspace = true }
transpile_utils = { path = "../transpile_utils" }
