[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { workspace = true }
thiserror = { workspace = true }
# anyhow = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
deadpool-postgres = { workspace = true }
percent-encoding = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
nix = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
